# Generated by Django 4.0.1 on 2022-03-30 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ElectStore', '0004_remove_order_user_name_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
